x-logging: &logging
  driver: local
  options:
    max-file: 10

x-image-main: &image-main
  image: ghcr.io/shutter-network/snapshot:v1.0.0

x-image-assets: &image-assets
  image: ghcr.io/shutter-network/snapshot-assets:v1.0.0

x-shutter-environment: &shutter-environment
  - SHUTTER_DATABASEURL=postgres://postgres@db:5432/keyper
  - SHUTTER_ETHEREUM_PRIVATEKEY=${SIGNING_KEY}
  - SHUTTER_ETHEREUM_ETHEREUMURL=https://rpc.gnosis.gateway.fm
  - SHUTTER_SHUTTERMINT_SHUTTERMINTURL=http://chain:26657
  - SHUTTER_ETHEREUM_DEPLOYMENTDIR=/deployment/
  - SHUTTER_P2P_CUSTOMBOOTSTRAPADDRESSES=/dns4/boot1.snapshot.shutter.network/tcp/23003/p2p/12D3KooWGkX3z2kffawGBVQ9w8ByniHxff6whoTPMyhC61aYABfD,/dns4/boot2.snapshot.shutter.network/tcp/23003/p2p/12D3KooWNeRXuJ4iDz5BAaVCVQ8qLesgmXVn77fjpEXmVktuMy9H
  - SHUTTER_P2P_LISTENADDRESSES=/ip4/0.0.0.0/tcp/23003
  - SHUTTER_INSTANCEID=555
  - SHUTTER_METRICS_ENABLED=${METRICS_ENABLED}

x-shuttermint-environment: &shuttermint-environment
  - SEED_NODES=859f786077eaa16658cb9f09f072cd66ec15dff3@boot2.snapshot.shutter.network:26656,d8ab66b14697a236a4b3cffda946d19d22ac7458@boot1.snapshot.shutter.network:26656
  - SHUTTERMINT_MONIKER=${KEYPER_NAME:-$(openssl rand -hex 8)}
  - PUBLIC_IP=${PUBLIC_IP}
  - METRICS_ENABLED=${METRICS_ENABLED}

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./scripts/keyper-db-init.sh:/docker-entrypoint-initdb.d/keyper-db-init.sh
    healthcheck:
      test: pg_isready -U postgres
    logging: *logging

  assets:
    <<: *image-assets
    command: "sleep infinity"
    stop_grace_period: "0s"

  keyper-create-config:
    <<: *image-main
    entrypoint:
      - /rolling-shutter
      - snapshotkeyper
    environment: *shutter-environment
    volumes:
      - ./config:/config
    command: "generate-config --output /config/generated.toml"

  keyper-initdb:
    <<: *image-main
    entrypoint:
      - /rolling-shutter
      - snapshotkeyper
    environment: *shutter-environment
    volumes:
      - ./config:/config
    command: "initdb --config /config/generated.toml"
    depends_on:
      db:
        condition: service_healthy
      keyper-create-config:
        condition: service_started

  chain-init:
    <<: *image-main
    entrypoint:
      - /rolling-shutter
      - chain
    volumes_from:
      - assets:ro
    environment: *shuttermint-environment
    volumes:
      - ./data/chain:/chain
    command: "init --root /chain --genesis-keyper ${GENESIS_KEYPER} --blocktime ${SM_BLOCKTIME} --listen-address tcp://0.0.0.0:26657 --role validator"
    depends_on:
      keyper-initdb:
        condition: service_completed_successfully

  keyper-config-dump:
    <<: *image-main
    entrypoint:
      - /rolling-shutter
      - snapshotkeyper
    command: "dump-config --config /config/generated.toml --output /config/keyper.toml"
    environment: *shutter-environment
    volumes_from:
      - assets:ro
    volumes:
      - ./config:/config
    depends_on:
      keyper-create-config:
        condition: service_started
      assets:
        condition: service_started

  config-publickey:
    image: busybox
    command: "./config_script.sh"
    volumes:
      - ./scripts/config_script.sh:/config_script.sh
      - ./data:/data
      - ./config:/config
    depends_on:
      keyper-config-dump:
        condition: service_started
      chain-init:
        condition: service_completed_successfully
      assets:
        condition: service_started

  config-chain:
    image: busybox
    command: "./shuttermint_config.sh"
    environment: *shuttermint-environment
    volumes:
      - ./scripts/shuttermint_config.sh:/shuttermint_config.sh
      - ./data:/data
    depends_on:
      chain-init:
        condition: service_completed_successfully
      assets:
        condition: service_started

  chain:
    <<: *image-main
    restart: always
    entrypoint:
      - /rolling-shutter
      - chain
    volumes_from:
      - assets:ro
    ports:
      - "${PUBLIC_IP}:26656:26656"
      - "${METRICS_LISTEN_IP}:26660:26660"
    volumes:
      - ./data/chain:/chain
    command: "--config /chain/config/config.toml"
    depends_on:
      assets:
        condition: service_started
      config-publickey:
        condition: service_completed_successfully
      config-chain:
        condition: service_completed_successfully
    logging: *logging

  keyper:
    <<: *image-main
    restart: always
    entrypoint:
      - /rolling-shutter
      - snapshotkeyper
    command: "--config /config/keyper.toml"
    volumes_from:
      - assets:ro
    volumes:
      - ./config:/config
    ports:
      - "${PUBLIC_IP}:23003:23003"
      - "${METRICS_LISTEN_IP}:9100:9100"
    depends_on:
      db:
        condition: service_healthy
      chain:
        condition: service_started
      assets:
        condition: service_started
      config-publickey:
        condition: service_started
    logging: *logging
