services:
  chain:
    logging: !override
      driver: loki
      options:
        loki-url: ${LOKI_URL}
        loki-external-labels: keyper_name=${KEYPER_NAME}

  keyper:
    logging: !override
      driver: loki
      options:
        loki-url: ${LOKI_URL}
        loki-external-labels: keyper_name=kpr-${KEYPER_NAME}